proxy:
  title: Aplicativo Exemplo
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  admin-groups: admins
  # Example: 'simple' authentication configuration
  users:
    - name: admin
      password: password
      groups: admins
    - name: teste
      password: teste
      groups: admins
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
    - id: 01_hello
      display-name: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
      container-image: openanalytics/shinyproxy-demo
      access-groups: admins
    - id: 06_tabsets
      container-cmd: [ "R", "-e", "shinyproxy::run_06_tabsets()" ]
      container-image: openanalytics/shinyproxy-demo
      access-groups: admins
    - id: Aplicativo_Exemplo
      container-cmd: [ "R", "-e", "shiny::runApp('/root/euler')" ]
      container-image: imagem-aplicacao-psi5120
      logo-url:  http://sites.usp.br/psi/wp-content/plugins/usp-theme-option-v2/images/usp-logo.png
      access-groups: [admins]

logging:
  file:
    name: shinyproxy.log

